YEAR_DAYS = 365
RATE_FROM_NAME_COLUMN = 'from_name'
RATE_TO_NAME_COLUMN = 'to_name'
RATE_DATE_COLUMN = 'dt'
RATE_PRICE_COLUMN = 'price'
RATE_VOLUME_COLUMN = 'volume'
POSITION_VOLUME_COLUMN = 'volume'
